[package]
name = "rust_satellite_wrapper"
version = "0.1.0"
authors = ["Rich Infante <rich@richinfante.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
satellite = { git = "https://github.com/richinfante/satellite-rs.git", branch = "master" }
chrono = "0.4"
